env:
  11111
spring:
  application:
    name: eval-auth
  #data:
    #elasticsearch:
      #cluster-name: eval
      #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
      #cluster-nodes: 127.0.0.1: 9300
  rabbitmq:
      host: localhost
      port: 5672
      username: admin
      password: admin
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/eval?useSSL=false&serverTimezone=UTC&allowMultiQueries=true

    #username: evalowner
    #password: c3U4xRaMM10rSQMmk
    #url: jdbc:mysql://rm-bp1lt3gi5m0570f24o.mysql.rds.aliyuncs.com:3306/eval?useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    # 配置初始化大小、最小、最大
    maxActive: 20
    initialSize: 1
    minIdle: 1
    # 配置监控统计拦截的filters
    filters: stat
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 校验语句
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    show-sql: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  zipkin:
    base-url: http://127.0.0.1:7777/
logging:
  level:
     com.sjy.eval.auth.mapper: debug
server:
  port: 9999
feign:
  hystrix:
      enabled: true
mybatis-plus:
  mapper-locations: classpath*:/mybatis/*Mapper.xml
  type-aliases-package: com.sjy.eval.auth.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
